### DISCUSSION TITLE
How to change upside down tab titles or remove  menu items on blog page?

### DISCUSSION THREAD

**Discussion by mohammadRezaeian** [MrGreensWorkshop/MrGreen-JekyllTheme#112] [How to] [answered]
Hi, thanks for create this project
I'm trying to edit this project, I want to remove Category Tabs  and change tab names.
To do that, I tried to change the file tabs/index.html in _site directory.
But when I try to build with this command, changes go back to the previous state.
```shell
bundle exec jekyll serve --watch --host 0.0.0.0 --safe
```

**Comment by MrGreensWorkshop** [comment, marked as answer]
Hi, first of all, _site folder is output folder. You can't change anything in there.

My advice is to use a good editor like VS Code, so you can use the search function.
If you search "Categories" you can find [this file](https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/tree/main/_includes/post-list/upside-down-tabs.html). If you want to remove category tab of upside down menu, this is where you need to make changes.

if you want to change the tab names, please check [this file](https://github.com/MrGreensWorkshop/MrGreen-JekyllTheme/blob/main/_data/lang/en.yml).

```yaml
  upside_down_tabs:
    tab:
      all: All
      categories: Categories #Change here
      tags: Tags
      years: Years
      clear: Clear
      close: Close
```

if that's what you're trying to achieve?
