### DISCUSSION TITLE
How to set the site URL to https://your_github_user_name.github.io/NameProject

### DISCUSSION THREAD

**Discussion by Esanpons** [MrGreensWorkshop/MrGreen-JekyllTheme#195] [How to] [answered]
Good morning,

I'm just starting now, and first of all I want to thank you not only for the template that is very cool, but for all the informative material that you have linked to it and the ease of many of the changes.

Let's go a bit to the mess, my query is the following.

In the url yes or if it has to have this structure "https://your_github_user_name.github.io" at least that's what you say in your videos and manuals.

But is there a way to make the URL "https://your_github_user_name.github.io/NameProject"?

Just like you can do with the Pages, just put the nick or also the name of the project.

Thank you so much

**Comment by MrGreensWorkshop** [comment]
>https://your_github_user_name.github.io/NameProject

Hi, that's possible, but considering the impact on search engine optimization, not recommended. (SEO robots.txt etc.) If you don't care about that, you can go for it.

Considering that people who come here mostly not familiar with GitHub pages, Jekyll, SEO etc. I decided to not document it. Those familiar with GitHub pages already know.

**Reply by Esanpons** [reply]
The problem is that if I change the project so much I give it another name and in the _config.yml it also doesn't work for me then the web and I don't know why.

**Reply by MrGreensWorkshop** [reply, marked as answer]
I just checked _config.yml again. This is how it's done. Comments are loud and clear.

```yml
# your web site url
# for GitHub Pages, url: "https://your_github_user_name.github.io"
url: "https://your_github_user_name.github.io"

# path to this site
# if your page is located at https://your_github_user_name.github.io/blog, then set baseurl: "/blog"
baseurl: "/NameProject"
```
You can learn more about _config.yml by visiting jekyll docs. https://jekyllrb.com/docs/
